/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;


/**
 *
 * @author andre
 */
public class TelaCursosDisp extends javax.swing.JFrame {
    private Usuario logado;
    /**
     * Creates new form TelaCursosDisp
     */
    public TelaCursosDisp() {
        super ("Cursos disponíveis");
        initComponents();
        buscarCursos();
        setLocationRelativeTo(null);
        txtDescricao.setWrapStyleWord(true);
        txtDescricao.setLineWrap(true);
        
        
    }

    TelaCursosDisp(Usuario logado) {
        super ("Cursos disponíveis");
        initComponents();
        buscarCursos();
        setLocationRelativeTo(null);
        txtDescricao.setWrapStyleWord(true);
        txtDescricao.setLineWrap(true);
        this.logado = logado;
    }
    private void buscarCursos (){
        try{
            DAO dao = new DAO();
            Cursos [] cursos = dao.obterCursos();
            cbCursos.setModel(new DefaultComboBoxModel<>(cursos));
        }
        catch (Exception e){
        JOptionPane.showMessageDialog(null, "Cursos indisponíveis, tente novamente mais tarde.");
        e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbCursos = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        txtAulas = new javax.swing.JLabel();
        txtCategoria = new javax.swing.JLabel();
        txtNome = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();
        imaFundoCursosDisp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbCursos.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                cbCursosCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        cbCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCursosActionPerformed(evt);
            }
        });
        getContentPane().add(cbCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 300, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Categoria:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Quantidade de aulas:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Descrição:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Nome do curso:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        btnCadastrar.setText("Me Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 110, 25));

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 110, 25));

        txtAulas.setBackground(new java.awt.Color(255, 255, 255));
        txtAulas.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtAulas.setForeground(new java.awt.Color(0, 0, 0));
        txtAulas.setText("exemplo");
        jPanel1.add(txtAulas, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));

        txtCategoria.setBackground(new java.awt.Color(255, 255, 255));
        txtCategoria.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtCategoria.setForeground(new java.awt.Color(0, 0, 0));
        txtCategoria.setText("exemplo");
        jPanel1.add(txtCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        txtNome.setBackground(new java.awt.Color(255, 255, 255));
        txtNome.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtNome.setForeground(new java.awt.Color(0, 0, 0));
        txtNome.setText("exemplo");
        jPanel1.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        txtDescricao.setColumns(20);
        txtDescricao.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtDescricao.setRows(5);
        jScrollPane1.setViewportView(txtDescricao);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 220, 110));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 540, 230));

        imaFundoCursosDisp.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://cdn.discordapp.com/attachments/1084193880951504908/1111060427695198329/TelaCursosDisp.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(imaFundoCursosDisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbCursosCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_cbCursosCaretPositionChanged
        
    }//GEN-LAST:event_cbCursosCaretPositionChanged

    private void cbCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCursosActionPerformed
        int id = cbCursos.getSelectedIndex();
        try{
            DAO dao = new DAO();
            Cursos [] cursos = dao.obterCursos();
            txtAulas.setText(Integer.toString((cursos[id].getQtdAulas())));
            txtCategoria.setText(cursos[id].getTipo());
            txtNome.setText(cursos[id].getNome());
            txtDescricao.setText(cursos[id].getDescricao());        
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Cursos indisponíveis, tente novamente mais tarde.");
            e.printStackTrace();    
        }
    }//GEN-LAST:event_cbCursosActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        TelaMenu tm = new TelaMenu(logado);
        tm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        DAO dao = new DAO();
        if(logado.getCurso1().equals(" ")){
            logado.setCurso1(txtNome.getText());              
            JOptionPane.showMessageDialog(null,"Cadastrado com sucesso!");
        }
        else if(logado.getCurso2().equals(" ")){
            logado.setCurso2(txtNome.getText());
            if(logado.getCurso1().equals(logado.getCurso2())){
                JOptionPane.showMessageDialog(null,"Você já está cadastrado nesse curso!");
                logado.setCurso2(" ");
                }
            else{
                JOptionPane.showMessageDialog(null,"Cadastrado com sucesso!");
            }
        }
        else if(logado.getCurso3().equals(" ")){
            logado.setCurso3(txtNome.getText());
            if(logado.getCurso3().equals(logado.getCurso2())||logado.getCurso3().equals(logado.getCurso1())){ 
            JOptionPane.showMessageDialog(null,"Você já está cadastrado nesse curso!");
            logado.setCurso3(" ");
            }
            else{
                JOptionPane.showMessageDialog(null,"Cadastrado com sucesso!");
            }
        }
        else if(logado.getCurso4().equals(" ")){
            logado.setCurso4(txtNome.getText());
            if(logado.getCurso4().equals(logado.getCurso3())||logado.getCurso4().equals(logado.getCurso2())||logado.getCurso4().equals(logado.getCurso1())){ 
                JOptionPane.showMessageDialog(null,"Você já está cadastrado nesse curso!");
                logado.setCurso4(" ");
                }
            else{
                JOptionPane.showMessageDialog(null,"Cadastrado com sucesso!");
            }
        }
        try {
            dao.addMeuCurso(logado);
        } catch (Exception ex) {
            Logger.getLogger(TelaCursosDisp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCursosDisp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCursosDisp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCursosDisp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCursosDisp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCursosDisp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<Cursos> cbCursos;
    private javax.swing.JLabel imaFundoCursosDisp;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel txtAulas;
    private javax.swing.JLabel txtCategoria;
    private javax.swing.JTextArea txtDescricao;
    private javax.swing.JLabel txtNome;
    // End of variables declaration//GEN-END:variables
}
