/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author andre
 */
public class TelaMenuAdm extends javax.swing.JFrame {
    private Administrador admlogado;
    /**
     * Creates new form TelaMenuAdm
     */
    public TelaMenuAdm() {
        super ("Menu Adm"); 
        initComponents();        
        setLocationRelativeTo(null);
        
    }
    public TelaMenuAdm(Administrador admlogado) {
        super ("Menu Adm"); 
        initComponents();        
        setLocationRelativeTo(null);       
        this.admlogado = admlogado;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMostrarAluno = new javax.swing.JButton();
        btnCadCursos = new javax.swing.JButton();
        btnMinhasInfo = new javax.swing.JButton();
        btnAreaUser = new javax.swing.JButton();
        imgFundoMenuAdm = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMostrarAluno.setText("Mostrar alunos");
        btnMostrarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarAlunoActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrarAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 150, 70));

        btnCadCursos.setText("Cadastrar cursos");
        btnCadCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadCursosActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 150, 70));

        btnMinhasInfo.setText("Minhas informações");
        btnMinhasInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinhasInfoActionPerformed(evt);
            }
        });
        getContentPane().add(btnMinhasInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 150, 70));

        btnAreaUser.setText("Área do Aluno");
        btnAreaUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaUserActionPerformed(evt);
            }
        });
        getContentPane().add(btnAreaUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 150, 70));

        imgFundoMenuAdm.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://cdn.discordapp.com/attachments/1084193880951504908/1111062139340345415/synapses_3_1.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        imgFundoMenuAdm.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                imgFundoMenuAdmAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(imgFundoMenuAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarAlunoActionPerformed
        TelaMostrarAlunos tma = new TelaMostrarAlunos(admlogado);
        tma.setVisible(true);
        this.dispose();        
    }//GEN-LAST:event_btnMostrarAlunoActionPerformed

    private void btnCadCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadCursosActionPerformed
        TelaCadCursos tcc = new TelaCadCursos(admlogado);
        tcc.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnCadCursosActionPerformed

    private void imgFundoMenuAdmAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_imgFundoMenuAdmAncestorAdded
        
    }//GEN-LAST:event_imgFundoMenuAdmAncestorAdded

    private void btnAreaUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaUserActionPerformed
        Usuario logado = new Usuario(1,"adm","adm","adm","adm");
        TelaMenu tm = new TelaMenu(logado);
        tm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAreaUserActionPerformed

    private void btnMinhasInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinhasInfoActionPerformed
        TelaMinhasInfoAdm tmia = new TelaMinhasInfoAdm(admlogado);
        tmia.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMinhasInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenuAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenuAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenuAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenuAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenuAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAreaUser;
    private javax.swing.JButton btnCadCursos;
    private javax.swing.JButton btnMinhasInfo;
    private javax.swing.JButton btnMostrarAluno;
    private javax.swing.JLabel imgFundoMenuAdm;
    // End of variables declaration//GEN-END:variables
}
