/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class TelaMenu extends javax.swing.JFrame {
    private Usuario logado;
    public TelaMenu() {
        super ("Menu"); 
        initComponents();
        setLocationRelativeTo(null);
        
    }
    public TelaMenu(Usuario logado) {
        super ("Menu");
        initComponents();        
        setLocationRelativeTo(null);
        txtApresentacao.setText("<html>Olá "+ logado.getNome() +"! Seja bem-vindo ao SYNAPSES,O que você deseja fazer?</html>");
        this.logado = logado;
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCursosDisp = new javax.swing.JButton();
        btnMeusCursos = new javax.swing.JButton();
        btnExtra = new javax.swing.JButton();
        btnMinhasinfo = new javax.swing.JButton();
        txtApresentacao = new javax.swing.JLabel();
        imgFundoMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCursosDisp.setText("Cursos disponíveis");
        btnCursosDisp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCursosDispActionPerformed(evt);
            }
        });
        getContentPane().add(btnCursosDisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, 150, 70));

        btnMeusCursos.setText("Meus cursos");
        btnMeusCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMeusCursosActionPerformed(evt);
            }
        });
        getContentPane().add(btnMeusCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 150, 70));

        btnExtra.setText("Extra");
        btnExtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExtraActionPerformed(evt);
            }
        });
        getContentPane().add(btnExtra, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, 150, 70));

        btnMinhasinfo.setText("Minhas informações");
        btnMinhasinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinhasinfoActionPerformed(evt);
            }
        });
        getContentPane().add(btnMinhasinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 150, 70));

        txtApresentacao.setFont(new java.awt.Font("LCD", 0, 24)); // NOI18N
        txtApresentacao.setText("<html>Olá! Seja bem-vindo ao SYNAPSES,O que você deseja fazer?</html>");
        getContentPane().add(txtApresentacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 210, -1));

        imgFundoMenu.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://cdn.discordapp.com/attachments/1084193880951504908/1111061157386662048/TelaMenu_1.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        getContentPane().add(imgFundoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMeusCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMeusCursosActionPerformed
        TelaMeusCursos tmc = new TelaMeusCursos(logado);
        tmc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMeusCursosActionPerformed

    private void btnCursosDispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCursosDispActionPerformed
        TelaCursosDisp tcd = new TelaCursosDisp(logado);
        tcd.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnCursosDispActionPerformed

    private void btnMinhasinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinhasinfoActionPerformed
        TelaMinhasInfo tmi = new TelaMinhasInfo(logado);
        tmi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMinhasinfoActionPerformed

    private void btnExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExtraActionPerformed
        TelaExtra te = new TelaExtra(logado);
        te.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnExtraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCursosDisp;
    private javax.swing.JButton btnExtra;
    private javax.swing.JButton btnMeusCursos;
    private javax.swing.JButton btnMinhasinfo;
    private javax.swing.JLabel imgFundoMenu;
    private javax.swing.JLabel txtApresentacao;
    // End of variables declaration//GEN-END:variables
}
